from typing import Protocol, Dict, Any, List


class AgentRuntime(Protocol):
    async def create_thread(self) -> str: ...

    async def run_turn(self, thread_id: str, prompt: str, context: Dict[str, Any], skill: str) -> str: ...

    def events(self, thread_id: str, after: int = 0) -> List[Dict[str, Any]]: ...

    async def cancel(self, thread_id: str, turn_id: str) -> None: ...

    async def approve(self, approval_id: str) -> None: ...
